# -*- coding: utf-8 -*-
"""inference_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cJJqhp70V3e9XPfjYIPQYF6R6mj7MqX
"""

# ===================== КОД ДЛЯ ЗАПУСКА В GOOGLE COLAB =====================

# Монтирование Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Импорты
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
import numpy as np
import os

# ------------------- Архитектура модели (копия из ноутбука) -------------------
class Brain_Tumor_MRI_CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.pool1 = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.pool2 = nn.MaxPool2d(2, 2)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.pool3 = nn.MaxPool2d(2, 2)
        self.conv4 = nn.Conv2d(128, 256, kernel_size=3, padding=1)
        self.pool4 = nn.MaxPool2d(2, 2)

        self.dropout = nn.Dropout(0.5)

        self.fc1 = nn.Linear(256 * 14 * 14, 1024)
        self.fc2 = nn.Linear(1024, 256)
        self.fc3 = nn.Linear(256, 64)
        self.fc4 = nn.Linear(64, 5)   # 5 классов

    def forward(self, x):
        x = self.pool1(F.relu(self.conv1(x)))
        x = self.pool2(F.relu(self.conv2(x)))
        x = self.pool3(F.relu(self.conv3(x)))
        x = self.pool4(F.relu(self.conv4(x)))
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = F.relu(self.fc2(x))
        x = self.dropout(x)
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return x

# ------------------- Словарь классов (порядок из обучения) -------------------
# Порядок: 0-glioblastoma, 1-glioma, 2-meningioma, 3-notumor, 4-pituitary
CLASS_NAMES_RU = {
    0: 'Глиобластома',
    1: 'Глиома',
    2: 'Менингиома',
    3: 'Без опухоли',
    4: 'Опухоль гипофиза'
}

# ------------------- Функция предсказания -------------------
def predict_tumor_type(image_path, model_path):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Загрузка модели
    model = Brain_Tumor_MRI_CNN().to(device)
    state_dict = torch.load(model_path, map_location=device)
    model.load_state_dict(state_dict)
    model.eval()

    # Загрузка и предобработка изображения
    img = Image.open(image_path).convert('L')          # Grayscale
    img = img.resize((224, 224), Image.BILINEAR)       # Resize
    img_array = np.array(img, dtype=np.float32) / 255.0
    img_array = (img_array - 0.5) / 0.5                 # Normalize (mean=0.5, std=0.5)
    img_tensor = torch.from_numpy(img_array).unsqueeze(0).unsqueeze(0).to(device)

    # Инференс
    with torch.no_grad():
        outputs = model(img_tensor)
        probs = F.softmax(outputs, dim=1)
        pred_class = torch.argmax(probs, dim=1).item()

    return CLASS_NAMES_RU[pred_class]

# ===================== УКАЖИТЕ ПУТИ К ФАЙЛАМ =====================
model_path = "/content/drive/MyDrive/Colab Notebooks/best_model.pth"
image_path = "/content/drive/MyDrive/Colab Notebooks/Brain_Tumor_MRI/Test/meningioma/1265.jpg"

# ===================== ЗАПУСК =====================
if not os.path.exists(model_path):
    print(f"Ошибка: файл модели не найден по пути {model_path}")
elif not os.path.exists(image_path):
    print(f"Ошибка: файл изображения не найден по пути {image_path}")
else:
    result = predict_tumor_type(image_path, model_path)
    print(result)